### ISSUE TITLE
AnalysisException: Cannot compute LIBRARY_ELEMENT for Instance of 'AssetBasedSource'

### ISSUE THREAD

**Issue by long1eu** [davidmarne/flutter_built_redux#18]
I'm getting this when i try to run my watcher.
```
Future<Null> main(List<String> args) async {
  await watch(<BuildAction>[
    new BuildAction(
        new PartBuilder(<Generator>[
          const JsonSerializableGenerator(),
          const BuiltValueGenerator(),
          new BuiltReduxGenerator(),
        ]),
        'my_app',
        inputs: const <String>['lib/**/*.dart'])
  ], deleteFilesByDefault: true);
}
```

```
[SEVERE] Instance of 'PartBuilder' on my_app|lib/actions/actions.dart: 
AnalysisException: Cannot compute LIBRARY_ELEMENT for Instance of 'AssetBasedSource'
Caused by Unexpected exception while performing ResolveUnitTypeNamesTask for source built_collection|lib/src/set/built_set.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:22)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:730:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:697:12)
#6      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:167:25)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#8      ListIterable.toList (dart:_internal/iterable.dart:218)
#9      ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:168:10)
#10     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#12     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#13     _rootRunUnary (dart:async/zone.dart:1128)
#14     _CustomZone.runUnary (dart:async/zone.dart:1012)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#16     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#17     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#18     _Future._completeWithValue (dart:async/future_impl.dart:478)
#19     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#20     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#21     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     _CustomZone.runGuarded (dart:async/zone.dart:901)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by davidmarne** [comment]
Not sure. Seems like an issue with analyzer resolving types from built_collection.
I tried some test generation with BuiltSet as values in built_values and with BuiltSet as the generic type in ActionDispatcher payloads and ran into no issues. 

I was successful using built_redux 7.3.5 on dart 2.0.0-dev.20.0 and 1.24.3 with the following dependencies pinned:

```
analyzer:
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.30.0+4"
  build:
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.2"
  build_runner:
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.0+1"
  built_collection:
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.4"
  built_value:
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.1"
  built_value_generator:
    description:
      name: built_value_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.1"```

**Comment by davidmarne** [comment]
What are you pinned to for those dependencies?

**Comment by long1eu** [comment]
you are right I was using the example here:
https://github.com/brianegan/flutter_architecture_samples/blob/master/example/built_redux/pubspec.yaml
with this:
  flutter_built_redux: ^0.4.0
  built_redux: ^7.0.0
  built_value: ^4.3.2
  built_collection: ^2.0.0
Once I've upgraded everything, it works
